package io.github.libtmux.codegen.kotlin

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy

private const val QUERY_PACKAGE = "io.github.libtmux.kotlin.query"

/** The Java handle type each owner in `field-catalog.tsv` names, by its TSV spelling. */
private val JAVA_OWNERS: Map<String, ClassName> = mapOf(
    "Pane" to ClassName("io.github.libtmux", "Pane"),
    "Session" to ClassName("io.github.libtmux", "Session"),
    "Window" to ClassName("io.github.libtmux", "Window"),
    "Client" to ClassName("io.github.libtmux", "Client"),
)

/**
 * Builds one `FileSpec` per owner in `field-catalog.tsv`, each an extension property on the matching
 * wrapper type's companion — `Pane.command`, `Window.panes`, ... — delegating to the generated Java
 * `Pane_`/`Session_`/`Window_`/`Client_` field object directly, so the Kotlin and Java field
 * namespaces can never disagree (ruling 9). A property, not a member: the companion is empty by hand,
 * so nothing here can collide with a hand-written declaration.
 */
public fun generateFieldPropertyFiles(rows: List<FieldRow>): List<FileSpec> =
    rows.groupBy { it.owner }.entries.sortedBy { it.key }.map { (owner, ownerRows) ->
        val javaOwner = JAVA_OWNERS.getValue(owner)
        val kotlinOwner = ClassName(FACADE_PACKAGE, owner)
        val metamodel = ClassName("io.github.libtmux", "${owner}_")
        val file = FileSpec.builder(QUERY_PACKAGE, "${owner}Fields")
            .addFileComment(
                "GENERATED by :tools:kotlin-operation-codegen from field-catalog.tsv. Do not edit;\n" +
                    "regenerate with the generateFieldProperties Gradle task.",
            )
        ownerRows.forEach { row -> file.addProperty(fieldProperty(row, kotlinOwner, javaOwner, metamodel)) }
        file.build()
    }

private fun fieldProperty(row: FieldRow, kotlinOwner: ClassName, javaOwner: ClassName, metamodel: ClassName) =
    PropertySpec.builder(row.name, fieldType(row, javaOwner))
        .receiver(kotlinOwner.nestedClass("Companion"))
        .addModifiers(KModifier.PUBLIC)
        .addKdoc("%L\n", row.javadoc)
        .getter(
            com.squareup.kotlinpoet.FunSpec.getterBuilder()
                .addStatement("return %L(%T.${row.name}())", fieldWrapperName(row), metamodel)
                .build(),
        )
        .build()

private fun fieldType(row: FieldRow, javaOwner: ClassName) = when (row.kind) {
    "TEXT" -> ClassName(QUERY_PACKAGE, "TextField").parameterizedBy(javaOwner)
    "NUMBER" -> ClassName(QUERY_PACKAGE, "NumberField").parameterizedBy(javaOwner)
    "FLAG" -> ClassName(QUERY_PACKAGE, "FlagField").parameterizedBy(javaOwner)
    "-" -> when {
        row.relation.startsWith("to-many:") ->
            ClassName(QUERY_PACKAGE, "ToManyField")
                .parameterizedBy(javaOwner, JAVA_OWNERS.getValue(row.relation.removePrefix("to-many:")))
        row.relation.startsWith("to-one:") ->
            ClassName(QUERY_PACKAGE, "ToOneField")
                .parameterizedBy(javaOwner, JAVA_OWNERS.getValue(row.relation.removePrefix("to-one:")))
        else -> error("row '${row.name}' on '${row.owner}' has kind '-' but no relation: ${row.relation}")
    }
    else -> error("unrecognized field kind '${row.kind}' for '${row.name}' on '${row.owner}'")
}

private fun fieldWrapperName(row: FieldRow): String = when (row.kind) {
    "TEXT" -> "TextField"
    "NUMBER" -> "NumberField"
    "FLAG" -> "FlagField"
    "-" -> if (row.relation.startsWith("to-many:")) "ToManyField" else "ToOneField"
    else -> error("unrecognized field kind '${row.kind}'")
}
