package io.github.libtmux.codegen.kotlin

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.INT
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LIST
import com.squareup.kotlinpoet.LONG
import com.squareup.kotlinpoet.MAP
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.UNIT

/** The package every hand-written wrapper class, and everything this tool generates, lives in. */
public const val FACADE_PACKAGE: String = "io.github.libtmux.kotlin"

/** Every Java handle type this generator knows how to wrap and unwrap. */
internal val WRAPPED_HANDLES: Map<String, ClassName> = mapOf(
    "io.github.libtmux.Server" to ClassName(FACADE_PACKAGE, "Server"),
    "io.github.libtmux.Session" to ClassName(FACADE_PACKAGE, "Session"),
    "io.github.libtmux.Window" to ClassName(FACADE_PACKAGE, "Window"),
    "io.github.libtmux.Pane" to ClassName(FACADE_PACKAGE, "Pane"),
    "io.github.libtmux.Client" to ClassName(FACADE_PACKAGE, "Client"),
    "io.github.libtmux.control.ControlClient" to ClassName(FACADE_PACKAGE, "ControlClient"),
)

/** Kinds the generator mirrors as a `suspend` extension function. Everything else is handwritten. */
private val GENERATED_KINDS = setOf("READ", "MUTATION")

private fun classNameOf(fqcn: String): ClassName {
    val simple = fqcn.substringAfterLast('.')
    val pkg = fqcn.removeSuffix(".$simple")
    return ClassName(pkg, simple)
}

private fun kotlinTypeName(type: JavaType): TypeName = when (type) {
    JavaType.Void -> UNIT
    is JavaType.Primitive -> ClassName("kotlin", type.kotlinName)
    is JavaType.Opaque -> when (type.fqcn) {
        "java.lang.String" -> STRING
        "java.time.Duration" -> ClassName("kotlin.time", "Duration")
        else -> WRAPPED_HANDLES[type.fqcn] ?: classNameOf(type.fqcn)
    }
    is JavaType.ListOf -> LIST.parameterizedBy(kotlinTypeName(type.element))
    is JavaType.MapOf -> MAP.parameterizedBy(kotlinTypeName(type.key), kotlinTypeName(type.value))
    is JavaType.OptionalOf -> kotlinTypeName(type.element).copy(nullable = true)
    JavaType.OptionalInt -> INT.copy(nullable = true)
    JavaType.OptionalLong -> LONG.copy(nullable = true)
    is JavaType.FilterExprOf ->
        ClassName("io.github.libtmux.query", "FilterExpr").parameterizedBy(classNameOf(type.elementFqcn))
    is JavaType.ArrayOf -> kotlinTypeName(type.element)
}

/** Whether wrapping this catalog operation's owner is something this generator recognizes. */
public fun isGeneratable(operation: CatalogOperation): Boolean =
    operation.kind in GENERATED_KINDS && WRAPPED_HANDLES.containsKey(operation.owner)

/**
 * Builds one `FileSpec` per owner, each holding every [isGeneratable] operation for that owner as a
 * `suspend` extension function on the matching wrapper class. Ruling 4's collision rule is what makes
 * this safe to regenerate: these are always extensions, never members, so a hand-written member of
 * the same name silently wins were one to collide, and the module's `allWarningsAsErrors` build turns
 * that silence into a build failure instead.
 */
public fun generateFiles(catalog: Catalog): List<FileSpec> {
    val byOwner = catalog.operations.filter(::isGeneratable).groupBy { it.owner }
    return byOwner.entries.sortedBy { it.key }.map { (owner, operations) ->
        val handle = WRAPPED_HANDLES.getValue(owner)
        val file = FileSpec.builder(FACADE_PACKAGE, "${handle.simpleName}Operations")
            .addFileComment(
                "GENERATED by :tools:kotlin-operation-codegen from operation-catalog.json. Do not edit;\n" +
                    "regenerate with the generateOperationWrappers Gradle task.",
            )
            .addImport("kotlinx.coroutines", "runInterruptible")
            .addImport("kotlin.time", "toJavaDuration")
        operations.sortedWith(compareBy({ it.name }, { it.parameters.size }))
            .forEach { file.addFunction(generateFunction(it, handle)) }
        file.build()
    }
}

private fun generateFunction(operation: CatalogOperation, owner: ClassName): FunSpec {
    val serverExpr = if (owner.simpleName == "Server") "this" else "this.server"
    val dispatcherExpr = if (owner.simpleName == "Server") "policy.commands" else "server.policy.commands"

    val builder = FunSpec.builder(operation.name)
        .addModifiers(KModifier.PUBLIC, KModifier.SUSPEND)
        .receiver(owner)
    if (operation.summary.isNotBlank()) {
        builder.addKdoc("%L\n", javadocToKdoc(operation.summary))
    }

    val callArguments = mutableListOf<String>()
    for (parameter in operation.parameters) {
        val parsed = parseJavaType(parameter.type)
        val isVararg = operation.varargs && parsed is JavaType.ArrayOf
        val elementType = if (parsed is JavaType.ArrayOf) parsed.element else parsed
        val paramSpec = ParameterSpec.builder(parameter.name, kotlinTypeName(elementType))
        if (isVararg) paramSpec.addModifiers(KModifier.VARARG)
        builder.addParameter(paramSpec.build())
        callArguments += javaCallArgument(parameter.name, elementType, spread = isVararg)
    }

    val returnType = parseJavaType(operation.returns.type)
    if (returnType != JavaType.Void) {
        builder.returns(kotlinTypeName(returnType))
    }
    val javaCall = "java.${operation.name}(${callArguments.joinToString(", ")})"
    val wrapped = wrapReturn(javaCall, returnType, serverExpr)
    builder.addStatement("return runInterruptible(%L) { %L }", dispatcherExpr, wrapped)
    return builder.build()
}

private fun javaCallArgument(name: String, type: JavaType, spread: Boolean): String {
    val prefix = if (spread) "*" else ""
    val expression = when {
        type is JavaType.Opaque && WRAPPED_HANDLES.containsKey(type.fqcn) -> "$name.java"
        type is JavaType.Opaque && type.fqcn == "java.time.Duration" -> "$name.toJavaDuration()"
        else -> name
    }
    return "$prefix$expression"
}

private fun wrapReturn(javaCall: String, type: JavaType, serverExpr: String): String = when (type) {
    JavaType.Void -> javaCall
    is JavaType.Opaque ->
        WRAPPED_HANDLES[type.fqcn]?.let { "${it.simpleName}($javaCall, $serverExpr)" } ?: javaCall
    is JavaType.ListOf -> {
        val element = type.element
        if (element is JavaType.Opaque && WRAPPED_HANDLES.containsKey(element.fqcn)) {
            "$javaCall.map { ${WRAPPED_HANDLES.getValue(element.fqcn).simpleName}(it, $serverExpr) }"
        } else {
            javaCall
        }
    }
    is JavaType.OptionalOf -> {
        val element = type.element
        val mapped = if (element is JavaType.Opaque && WRAPPED_HANDLES.containsKey(element.fqcn)) {
            "$javaCall.map { ${WRAPPED_HANDLES.getValue(element.fqcn).simpleName}(it, $serverExpr) }"
        } else {
            javaCall
        }
        "$mapped.orElse(null)"
    }
    JavaType.OptionalInt -> "$javaCall.let { if (it.isPresent) it.asInt else null }"
    JavaType.OptionalLong -> "$javaCall.let { if (it.isPresent) it.asLong else null }"
    is JavaType.MapOf, is JavaType.Primitive, is JavaType.FilterExprOf, is JavaType.ArrayOf -> javaCall
}
