/** Generates `PaneFields`/`SessionFields`/`WindowFields`/`ClientFields` from
  * `field-catalog.tsv`, one `def` per row, each forwarding to the Java field
  * descriptor (`Pane_.id()`, ...) the same TSV already generates on the Java
  * side. Kept in a separate combined file and package
  * (`io.github.libtmux.scaladsl.generated`) rather than alongside the
  * handwritten `object Pane`, since Scala 3 only treats a class and object of
  * the same name as companions when they share one file: `Pane.scala`'s own
  * `object Pane` re-exports these with `export generated.PaneFields.*` instead
  * of hosting them directly.
  */
object ScalaFieldCodegen {

  private val owners: Vector[(String, String, String)] = Vector(
    ("Pane", "JavaPane", "PaneFields"),
    ("Session", "JavaSession", "SessionFields"),
    ("Window", "JavaWindow", "WindowFields"),
    ("Client", "JavaClient", "ClientFields")
  )

  private def wrapperType(row: FieldRow, javaOwner: String): String =
    row.kind match {
      case "TEXT" =>
        s"_root_.io.github.libtmux.scaladsl.query.Fields.TextField[$javaOwner]"
      case "NUMBER" =>
        s"_root_.io.github.libtmux.scaladsl.query.Fields.NumberField[$javaOwner]"
      case "FLAG" =>
        s"_root_.io.github.libtmux.scaladsl.query.Fields.FlagField[$javaOwner]"
      case "-" =>
        row.relation.split(":", 2) match {
          case Array("to-many", target) =>
            s"_root_.io.github.libtmux.scaladsl.query.Fields.ToManyRef[$javaOwner, Java$target]"
          case Array("to-one", target) =>
            s"_root_.io.github.libtmux.scaladsl.query.Fields.ToOneRef[$javaOwner, Java$target]"
          case _ =>
            throw new IllegalArgumentException(
              "field-catalog.tsv relation must be to-many:X or to-one:X: " + row.relation
            )
        }
      case other =>
        throw new IllegalArgumentException(
          "field-catalog.tsv kind must be TEXT, NUMBER, FLAG or -: " + other
        )
    }

  private def scaladoc(row: FieldRow): String =
    if (row.javadoc.isEmpty) ""
    else s"  /** ${row.javadoc} */\n"

  private def field(
      row: FieldRow,
      javaOwner: String,
      javaOwnerUnderscore: String
  ): String = {
    val tpe = wrapperType(row, javaOwner)
    s"${scaladoc(row)}  def ${row.name}: $tpe =\n" +
      s"    new $tpe($javaOwnerUnderscore.${row.name}())"
  }

  private def fieldsObject(
      owner: String,
      javaOwner: String,
      objectName: String,
      rows: Vector[FieldRow]
  ): String = {
    val matching = rows.filter(_.owner == owner)
    require(
      matching.nonEmpty,
      "field-catalog.tsv has no rows for owner " + owner
    )
    val javaOwnerUnderscore = "_root_.io.github.libtmux." + owner + "_"
    val body =
      matching.map(field(_, javaOwner, javaOwnerUnderscore)).mkString("\n\n")
    s"""object $objectName {
       |$body
       |}""".stripMargin
  }

  /** One combined file: `import`s the four Java handle aliases once, then one
    * generated `object ...Fields` per owner.
    */
  def combinedFields(rows: Vector[FieldRow]): String = {
    val blocks = owners.map { case (owner, javaOwner, objectName) =>
      fieldsObject(owner, javaOwner, objectName, rows)
    }
    s"""package io.github.libtmux.scaladsl.generated
       |
       |// Generated by ScalaFieldCodegen from field-catalog.tsv. Not checked in; see project/ScalaFieldCodegen.scala.
       |
       |import io.github.libtmux.{
       |  Pane => JavaPane,
       |  Session => JavaSession,
       |  Window => JavaWindow,
       |  Client => JavaClient
       |}
       |
       |${blocks.mkString("\n\n")}
       |""".stripMargin
  }
}
